
raw_dir = fullfile('~', 'NIDM-Ex', 'BIDS_Data', 'DATA', 'BIDS');
results_dir = fullfile('~', 'NIDM-Ex', 'BIDS_Data','RESULTS', 'SOFTWARE_COMPARISON');


% [subjects, runs] = get_subjects_runs(raw_dir);

copy_gunzip(...
    fullfile(raw_dir, 'ds001_R1.1.0'), ...
    fullfile(results_dir, 'ds001', 'SPM', 'PREPROCESSING'));

% 
% CondNms={...
%     'pumps_fixed',...
%     'pumps_demean',...
%     'pumps_fixed_real_RT',...
%     'cash_fixed',...
%     'cash_demean',...
%     'cash_fixed_real_RT',...
%     'explode_fixed',...
%     'explode_demean',...
%     'control_pumps_fixed',... 
%     'control_pumps_demean',...
%     'control_pumps_fixed_real_RT'};

% Directory to store the onset files
onsetDir = fullfile(results_dir,'ds001','SPM','ONSETS');
FSLonsetDir = fullfile(results_dir,'ds001','FSL','ONSETS');

% Define conditions and parametric modulations (if any)
CondNames = {...
    {'pumps_fixed','pumps_demean'},...
    'pumps_fixed_real_RT',...
    {'cash_fixed','cash_demean'},...
    'cash_fixed_real_RT',...
    {'explode_fixed','explode_demean'},...
    {'control_pumps_fixed','control_pumps_demean'},...,
    'control_pumps_fixed_real_RT'};

create_onset_files(onsetDir, FSLonsetDir, CondNames)

