base_dir = '/home/maullz/NIDM-Ex/BIDS_Data';

raw_dir = fullfile(base_dir, 'DATA', 'BIDS');
results_dir = fullfile(base_dir, 'RESULTS', 'SOFTWARE_COMPARISON');

study_dir = fullfile(raw_dir, 'ds000001_R2.0.3');
spm_dir = fullfile(results_dir, 'ds001', 'SPM');
preproc_dir = fullfile(spm_dir, 'PREPROCESSING');
level1_dir = fullfile(spm_dir, 'LEVEL1');

% [subjects, runs] = get_subjects_runs(raw_dir);

% Add 'lib' folder to the matlab path
if ~exist('copy_gunzip', 'file')
    addpath(fullfile(fileparts(mfilename('fullpath')), 'lib'))
end

 copy_gunzip(...
    study_dir, ...
    preproc_dir);

% 
% CondNms={...
%     'pumps_fixed',...
%     'pumps_fixed_pmod',...
%     'pumps_RT',...
%     'cash_fixed',...
%     'cash_fixed_pmod',...
%     'cash_RT',...
%     'explode_fixed',...
%     'explode_fixed_pmod',...
%     'control_pumps_fixed',... 
%     'control_pumps_fixed_pmod',...
%     'control_pumps_RT'};

% Directory to store the onset files
onsetDir = fullfile(results_dir,'ds001','SPM','ONSETS');

% Define conditions and parametric modulations (if any)
CondNames = {...
    {{'pumps_fixed','pumps_demean'}, {'pumps_demean'}},...
    {'pumps_RT', {'pumps_demean', 'response_time'}},...
    {{'cash_fixed','cash_demean'}, {'cash_demean'}},...
    {'cash_RT', {'cash_demean', 'response_time'}},...
    {{'explode_fixed','explode_demean'}, {'explode_demean'}},...
    {{'control_pumps_fixed','control_pumps_demean'}, {'control_pumps_demean'}},...
    {'control_pumps_RT', {'control_pumps_demean', 'response_time'}}};

%create_onset_files(study_dir, onsetDir, CondNames);
run_subject_level_analyses(raw_dir, preproc_dir, 'template_ds001_SPM_level1', level1_dir);

run_group_level_analysis(raw_dir, level1_dir, 'template_ds001_SPM_level2', level2_dir);
%'/storage/essicd/data/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds001/SPM/LEVEL2/pumps_demean_vs_ctrl_demean'
