
raw_dir = fullfile('/home', 'maullz', 'NIDM-Ex', 'BIDS_Data', 'DATA', 'BIDS');
results_dir = fullfile('/home', 'maullz', 'NIDM-Ex', 'BIDS_Data','RESULTS', 'SOFTWARE_COMPARISON');
study_dir = fullfile(raw_dir, 'ds001_R1.1.0');

% [subjects, runs] = get_subjects_runs(raw_dir);

% Add 'lib' folder to the matlab path
if ~exist('copy_gunzip', 'file')
    addpath(fullfile(fileparts(mfilename('fullpath')), 'lib'))
end

% copy_gunzip(...
%    fullfile(raw_dir, 'ds001_R1.1.0'), ...
%    fullfile(results_dir, 'ds001', 'SPM', 'PREPROCESSING'));

% 
% CondNms={...
%     'pumps_fixed',...
%     'pumps_fixed_pmod',...
%     'pumps_RT',...
%     'cash_fixed',...
%     'cash_fixed_pmod',...
%     'cash_RT',...
%     'explode_fixed',...
%     'explode_fixed_pmod',...
%     'control_pumps_fixed',... 
%     'control_pumps_fixed_pmod',...
%     'control_pumps_RT'};

% Directory to store the onset files
onsetDir = fullfile(results_dir,'ds001','SPM','ONSETS');

% Define conditions and parametric modulations (if any)
CondNames = {...
    {{'pumps_fixed','pumps_demean'}, {'pumps_demean'}},...
    {'pumps_RT', {'pumps_demean', 'response_time'}},...
    {{'cash_fixed','cash_demean'}, {'cash_demean'}},...
    {'cash_RT', {'cash_demean', 'response_time'}},...
    {{'explode_fixed','explode_demean'}, {'explode_demean'}},...
    {{'control_pumps_fixed','control_pumps_demean'}, {'control_pumps_demean'}},...
    {'control_pumps_RT', {'control_pumps_demean', 'response_time'}}};

create_onset_files(study_dir, onsetDir, CondNames)

