
CondNms={...
    'pumps_fixed',...
    'pumps_demean',...
    'pumps_fixed_real_RT',...
    'cash_fixed',...
    'cash_demean',...
    'cash_fixed_real_RT',...
    'explode_fixed',...
    'explode_demean',...
    'control_pumps_fixed',... 
    'control_pumps_demean',...
    'control_pumps_fixed_real_RT'};

% Define parametric modulations (if any)
CondNames={...
    {CondNms{1},CondNms{2}},...
    CondNms{3},...
    {CondNms{4},CondNms{5}},...
    CondNms{6},...
    {CondNms{7},CondNms{8}},...
    {CondNms{9},CondNms{10}},...,
    CondNms{11}};

