cd /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL2

3dMVM -prefix Group -jobs 4   \
      -bsVars Agegroup               \
      -wsVars 'Incentive*Time'   \
      -dataTable                                            \
      Subj   Agegroup     Incentive    Time InputFile                 \
      s1     child         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[neutral#0_Tstat]'    \
      s1     child         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[neutral#1_Tstat]'    \
      s1     child         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[neutral#2_Tstat]'    \
      s1     child         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[neutral#3_Tstat]'    \
      s1     child         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[neutral#4_Tstat]'    \
      s1     child         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[neutral#5_Tstat]'    \
      s1     child         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[neutral#6_Tstat]'    \
      s1     child         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[neutral#7_Tstat]'    \
      s1     child         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[reward#0_Tstat]'     \
      s1     child         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[reward#1_Tstat]'     \
      s1     child         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[reward#2_Tstat]'     \
      s1     child         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[reward#3_Tstat]'     \
      s1     child         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[reward#4_Tstat]'     \
      s1     child         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[reward#5_Tstat]'     \
      s1     child         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[reward#6_Tstat]'     \
      s1     child         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-01/sub01.results/stats.sub01+tlrc'[reward#7_Tstat]'     \
      s2     child         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[neutral#0_Tstat]'    \
      s2     child         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[neutral#1_Tstat]'    \
      s2     child         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[neutral#2_Tstat]'    \
      s2     child         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[neutral#3_Tstat]'    \
      s2     child         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[neutral#4_Tstat]'    \
      s2     child         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[neutral#5_Tstat]'    \
      s2     child         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[neutral#6_Tstat]'    \
      s2     child         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[neutral#7_Tstat]'    \
      s2     child         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[reward#0_Tstat]'     \
      s2     child         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[reward#1_Tstat]'     \
      s2     child         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[reward#2_Tstat]'     \
      s2     child         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[reward#3_Tstat]'     \
      s2     child         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[reward#4_Tstat]'     \
      s2     child         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[reward#5_Tstat]'     \
      s2     child         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[reward#6_Tstat]'     \
      s2     child         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-02/sub02.results/stats.sub02+tlrc'[reward#7_Tstat]'     \
      s3     child         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[neutral#0_Tstat]'    \
      s3     child         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[neutral#1_Tstat]'    \
      s3     child         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[neutral#2_Tstat]'    \
      s3     child         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[neutral#3_Tstat]'    \
      s3     child         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[neutral#4_Tstat]'    \
      s3     child         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[neutral#5_Tstat]'    \
      s3     child         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[neutral#6_Tstat]'    \
      s3     child         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[neutral#7_Tstat]'    \
      s3     child         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[reward#0_Tstat]'     \
      s3     child         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[reward#1_Tstat]'     \
      s3     child         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[reward#2_Tstat]'     \
      s3     child         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[reward#3_Tstat]'     \
      s3     child         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[reward#4_Tstat]'     \
      s3     child         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[reward#5_Tstat]'     \
      s3     child         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[reward#6_Tstat]'     \
      s3     child         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-03/sub03.results/stats.sub03+tlrc'[reward#7_Tstat]'     \
      s4     child         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[neutral#0_Tstat]'    \
      s4     child         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[neutral#1_Tstat]'    \
      s4     child         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[neutral#2_Tstat]'    \
      s4     child         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[neutral#3_Tstat]'    \
      s4     child         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[neutral#4_Tstat]'    \
      s4     child         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[neutral#5_Tstat]'    \
      s4     child         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[neutral#6_Tstat]'    \
      s4     child         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[neutral#7_Tstat]'    \
      s4     child         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[reward#0_Tstat]'     \
      s4     child         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[reward#1_Tstat]'     \
      s4     child         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[reward#2_Tstat]'     \
      s4     child         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[reward#3_Tstat]'     \
      s4     child         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[reward#4_Tstat]'     \
      s4     child         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[reward#5_Tstat]'     \
      s4     child         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[reward#6_Tstat]'     \
      s4     child         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-04/sub04.results/stats.sub04+tlrc'[reward#7_Tstat]'     \
      s6     child         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[neutral#0_Tstat]'    \
      s6     child         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[neutral#1_Tstat]'    \
      s6     child         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[neutral#2_Tstat]'    \
      s6     child         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[neutral#3_Tstat]'    \
      s6     child         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[neutral#4_Tstat]'    \
      s6     child         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[neutral#5_Tstat]'    \
      s6     child         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[neutral#6_Tstat]'    \
      s6     child         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[neutral#7_Tstat]'    \
      s6     child         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[reward#0_Tstat]'     \
      s6     child         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[reward#1_Tstat]'     \
      s6     child         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[reward#2_Tstat]'     \
      s6     child         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[reward#3_Tstat]'     \
      s6     child         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[reward#4_Tstat]'     \
      s6     child         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[reward#5_Tstat]'     \
      s6     child         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[reward#6_Tstat]'     \
      s6     child         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-06/sub06.results/stats.sub06+tlrc'[reward#7_Tstat]'     \
      s8     adolescent    neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[neutral#0_Tstat]'    \
      s8     adolescent    neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[neutral#1_Tstat]'    \
      s8     adolescent    neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[neutral#2_Tstat]'    \
      s8     adolescent    neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[neutral#3_Tstat]'    \
      s8     adolescent    neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[neutral#4_Tstat]'    \
      s8     adolescent    neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[neutral#5_Tstat]'    \
      s8     adolescent    neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[neutral#6_Tstat]'    \
      s8     adolescent    neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[neutral#7_Tstat]'    \
      s8     adolescent    reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[reward#0_Tstat]'     \
      s8     adolescent    reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[reward#1_Tstat]'     \
      s8     adolescent    reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[reward#2_Tstat]'     \
      s8     adolescent    reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[reward#3_Tstat]'     \
      s8     adolescent    reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[reward#4_Tstat]'     \
      s8     adolescent    reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[reward#5_Tstat]'     \
      s8     adolescent    reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[reward#6_Tstat]'     \
      s8     adolescent    reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-08/sub08.results/stats.sub08+tlrc'[reward#7_Tstat]'     \
      s10    adolescent    neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[neutral#0_Tstat]'    \
      s10    adolescent    neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[neutral#1_Tstat]'    \
      s10    adolescent    neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[neutral#2_Tstat]'    \
      s10    adolescent    neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[neutral#3_Tstat]'    \
      s10    adolescent    neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[neutral#4_Tstat]'    \
      s10    adolescent    neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[neutral#5_Tstat]'    \
      s10    adolescent    neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[neutral#6_Tstat]'    \
      s10    adolescent    neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[neutral#7_Tstat]'    \
      s10    adolescent    reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[reward#0_Tstat]'     \
      s10    adolescent    reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[reward#1_Tstat]'     \
      s10    adolescent    reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[reward#2_Tstat]'     \
      s10    adolescent    reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[reward#3_Tstat]'     \
      s10    adolescent    reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[reward#4_Tstat]'     \
      s10    adolescent    reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[reward#5_Tstat]'     \
      s10    adolescent    reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[reward#6_Tstat]'     \
      s10    adolescent    reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-10/sub10.results/stats.sub10+tlrc'[reward#7_Tstat]'     \
      s11    adolescent    neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[neutral#0_Tstat]'    \
      s11    adolescent    neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[neutral#1_Tstat]'    \
      s11    adolescent    neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[neutral#2_Tstat]'    \
      s11    adolescent    neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[neutral#3_Tstat]'    \
      s11    adolescent    neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[neutral#4_Tstat]'    \
      s11    adolescent    neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[neutral#5_Tstat]'    \
      s11    adolescent    neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[neutral#6_Tstat]'    \
      s11    adolescent    neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[neutral#7_Tstat]'    \
      s11    adolescent    reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[reward#0_Tstat]'     \
      s11    adolescent    reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[reward#1_Tstat]'     \
      s11    adolescent    reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[reward#2_Tstat]'     \
      s11    adolescent    reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[reward#3_Tstat]'     \
      s11    adolescent    reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[reward#4_Tstat]'     \
      s11    adolescent    reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[reward#5_Tstat]'     \
      s11    adolescent    reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[reward#6_Tstat]'     \
      s11    adolescent    reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-11/sub11.results/stats.sub11+tlrc'[reward#7_Tstat]'     \
      s14    adolescent    neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[neutral#0_Tstat]'    \
      s14    adolescent    neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[neutral#1_Tstat]'    \
      s14    adolescent    neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[neutral#2_Tstat]'    \
      s14    adolescent    neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[neutral#3_Tstat]'    \
      s14    adolescent    neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[neutral#4_Tstat]'    \
      s14    adolescent    neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[neutral#5_Tstat]'    \
      s14    adolescent    neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[neutral#6_Tstat]'    \
      s14    adolescent    neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[neutral#7_Tstat]'    \
      s14    adolescent    reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[reward#0_Tstat]'     \
      s14    adolescent    reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[reward#1_Tstat]'     \
      s14    adolescent    reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[reward#2_Tstat]'     \
      s14    adolescent    reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[reward#3_Tstat]'     \
      s14    adolescent    reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[reward#4_Tstat]'     \
      s14    adolescent    reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[reward#5_Tstat]'     \
      s14    adolescent    reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[reward#6_Tstat]'     \
      s14    adolescent    reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-14/sub14.results/stats.sub14+tlrc'[reward#7_Tstat]'     \
      s17    adolescent    neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[neutral#0_Tstat]'    \
      s17    adolescent    neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[neutral#1_Tstat]'    \
      s17    adolescent    neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[neutral#2_Tstat]'    \
      s17    adolescent    neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[neutral#3_Tstat]'    \
      s17    adolescent    neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[neutral#4_Tstat]'    \
      s17    adolescent    neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[neutral#5_Tstat]'    \
      s17    adolescent    neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[neutral#6_Tstat]'    \
      s17    adolescent    neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[neutral#7_Tstat]'    \
      s17    adolescent    reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[reward#0_Tstat]'     \
      s17    adolescent    reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[reward#1_Tstat]'     \
      s17    adolescent    reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[reward#2_Tstat]'     \
      s17    adolescent    reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[reward#3_Tstat]'     \
      s17    adolescent    reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[reward#4_Tstat]'     \
      s17    adolescent    reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[reward#5_Tstat]'     \
      s17    adolescent    reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[reward#6_Tstat]'     \
      s17    adolescent    reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-17/sub17.results/stats.sub17+tlrc'[reward#7_Tstat]'     \
      s18    adult         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[neutral#0_Tstat]'    \
      s18    adult         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[neutral#1_Tstat]'    \
      s18    adult         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[neutral#2_Tstat]'    \
      s18    adult         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[neutral#3_Tstat]'    \
      s18    adult         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[neutral#4_Tstat]'    \
      s18    adult         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[neutral#5_Tstat]'    \
      s18    adult         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[neutral#6_Tstat]'    \
      s18    adult         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[neutral#7_Tstat]'    \
      s18    adult         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[reward#0_Tstat]'     \
      s18    adult         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[reward#1_Tstat]'     \
      s18    adult         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[reward#2_Tstat]'     \
      s18    adult         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[reward#3_Tstat]'     \
      s18    adult         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[reward#4_Tstat]'     \
      s18    adult         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[reward#5_Tstat]'     \
      s18    adult         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[reward#6_Tstat]'     \
      s18    adult         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-18/sub18.results/stats.sub18+tlrc'[reward#7_Tstat]'     \
      s19    adult         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[neutral#0_Tstat]'    \
      s19    adult         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[neutral#1_Tstat]'    \
      s19    adult         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[neutral#2_Tstat]'    \
      s19    adult         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[neutral#3_Tstat]'    \
      s19    adult         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[neutral#4_Tstat]'    \
      s19    adult         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[neutral#5_Tstat]'    \
      s19    adult         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[neutral#6_Tstat]'    \
      s19    adult         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[neutral#7_Tstat]'    \
      s19    adult         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[reward#0_Tstat]'     \
      s19    adult         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[reward#1_Tstat]'     \
      s19    adult         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[reward#2_Tstat]'     \
      s19    adult         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[reward#3_Tstat]'     \
      s19    adult         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[reward#4_Tstat]'     \
      s19    adult         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[reward#5_Tstat]'     \
      s19    adult         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[reward#6_Tstat]'     \
      s19    adult         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-19/sub19.results/stats.sub19+tlrc'[reward#7_Tstat]'     \
      s21    adult         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[neutral#0_Tstat]'    \
      s21    adult         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[neutral#1_Tstat]'    \
      s21    adult         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[neutral#2_Tstat]'    \
      s21    adult         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[neutral#3_Tstat]'    \
      s21    adult         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[neutral#4_Tstat]'    \
      s21    adult         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[neutral#5_Tstat]'    \
      s21    adult         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[neutral#6_Tstat]'    \
      s21    adult         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[neutral#7_Tstat]'    \
      s21    adult         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[reward#0_Tstat]'     \
      s21    adult         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[reward#1_Tstat]'     \
      s21    adult         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[reward#2_Tstat]'     \
      s21    adult         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[reward#3_Tstat]'     \
      s21    adult         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[reward#4_Tstat]'     \
      s21    adult         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[reward#5_Tstat]'     \
      s21    adult         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[reward#6_Tstat]'     \
      s21    adult         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-21/sub21.results/stats.sub21+tlrc'[reward#7_Tstat]'     \
      s22    adult         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[neutral#0_Tstat]'    \
      s22    adult         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[neutral#1_Tstat]'    \
      s22    adult         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[neutral#2_Tstat]'    \
      s22    adult         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[neutral#3_Tstat]'    \
      s22    adult         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[neutral#4_Tstat]'    \
      s22    adult         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[neutral#5_Tstat]'    \
      s22    adult         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[neutral#6_Tstat]'    \
      s22    adult         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[neutral#7_Tstat]'    \
      s22    adult         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[reward#0_Tstat]'     \
      s22    adult         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[reward#1_Tstat]'     \
      s22    adult         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[reward#2_Tstat]'     \
      s22    adult         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[reward#3_Tstat]'     \
      s22    adult         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[reward#4_Tstat]'     \
      s22    adult         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[reward#5_Tstat]'     \
      s22    adult         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[reward#6_Tstat]'     \
      s22    adult         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-22/sub22.results/stats.sub22+tlrc'[reward#7_Tstat]'     \
      s25    adult         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[neutral#0_Tstat]'    \
      s25    adult         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[neutral#1_Tstat]'    \
      s25    adult         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[neutral#2_Tstat]'    \
      s25    adult         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[neutral#3_Tstat]'    \
      s25    adult         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[neutral#4_Tstat]'    \
      s25    adult         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[neutral#5_Tstat]'    \
      s25    adult         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[neutral#6_Tstat]'    \
      s25    adult         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[neutral#7_Tstat]'    \
      s25    adult         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[reward#0_Tstat]'     \
      s25    adult         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[reward#1_Tstat]'     \
      s25    adult         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[reward#2_Tstat]'     \
      s25    adult         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[reward#3_Tstat]'     \
      s25    adult         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[reward#4_Tstat]'     \
      s25    adult         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[reward#5_Tstat]'     \
      s25    adult         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[reward#6_Tstat]'     \
      s25    adult         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-25/sub25.results/stats.sub25+tlrc'[reward#7_Tstat]'     \
      s26    adult         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[neutral#0_Tstat]'    \
      s26    adult         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[neutral#1_Tstat]'    \
      s26    adult         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[neutral#2_Tstat]'    \
      s26    adult         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[neutral#3_Tstat]'    \
      s26    adult         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[neutral#4_Tstat]'    \
      s26    adult         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[neutral#5_Tstat]'    \
      s26    adult         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[neutral#6_Tstat]'    \
      s26    adult         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[neutral#7_Tstat]'    \
      s26    adult         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[reward#0_Tstat]'     \
      s26    adult         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[reward#1_Tstat]'     \
      s26    adult         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[reward#2_Tstat]'     \
      s26    adult         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[reward#3_Tstat]'     \
      s26    adult         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[reward#4_Tstat]'     \
      s26    adult         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[reward#5_Tstat]'     \
      s26    adult         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[reward#6_Tstat]'     \
      s26    adult         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-26/sub26.results/stats.sub26+tlrc'[reward#7_Tstat]'     \
      s27    adult         neutral      t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[neutral#0_Tstat]'    \
      s27    adult         neutral      t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[neutral#1_Tstat]'    \
      s27    adult         neutral      t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[neutral#2_Tstat]'    \
      s27    adult         neutral      t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[neutral#3_Tstat]'    \
      s27    adult         neutral      t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[neutral#4_Tstat]'    \
      s27    adult         neutral      t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[neutral#5_Tstat]'    \
      s27    adult         neutral      t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[neutral#6_Tstat]'    \
      s27    adult         neutral      t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[neutral#7_Tstat]'    \
      s27    adult         reward       t0   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[reward#0_Tstat]'     \
      s27    adult         reward       t1   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[reward#1_Tstat]'     \
      s27    adult         reward       t2   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[reward#2_Tstat]'     \
      s27    adult         reward       t3   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[reward#3_Tstat]'     \
      s27    adult         reward       t4   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[reward#4_Tstat]'     \
      s27    adult         reward       t5   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[reward#5_Tstat]'     \
      s27    adult         reward       t6   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[reward#6_Tstat]'     \
      s27    adult         reward       t7   /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-27/sub27.results/stats.sub27+tlrc'[reward#7_Tstat]'     

# Create a group mask
3dMean -mask_inter -prefix mask `ls /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL1/sub-*/sub*.results/mask_group*.HEAD`

# Simulations for FWE corrected cluster-size inference
# 0.621678 5.83585 16.1792 is the average of the 3dFWHMx -acf calculations applied
# to the blur_est.sub_xxx.1D files for the 16 subjects
3dClustSim -both -mask mask+tlrc -acf 0.765135 3.87751 13.6935 -prefix ClustSim 

3dclust -1Dformat -nosum -1dindex 4 -1tindex 4 -2thresh -3.836 3.836 -dxyz=1 -savemask Positive_clust_mask 1.01 60 /home/maullz/NIDM-Ex/BIDS_Data/RESULTS/SOFTWARE_COMPARISON/ds120/AFNI/LEVEL2/Group+tlrc.HEAD

# Masking f_stat 
   3dcalc -a 'Group+tlrc[4]' -b 'mask+tlrc' \
            -expr 'a*b' -prefix Group_f_stat_masked -datum float   

# Binarizing both cluster masks
   3dcalc -a 'Positive_clust_mask+tlrc' -expr 'ispositive(a-0.5)' \
            -prefix Positive_binary_clust_mask                 
           
   3dcalc -a Positive_binary_clust_mask+tlrc -b Group_f_stat_masked+tlrc \
            -expr 'a*b' -prefix Group_positive_f_stat_clustered -datum float   

# Convert to NIFTI for upload to Neurovault
  3dAFNItoNIFTI -prefix Group_f_stat Group+tlrc"[4]"
  3dAFNItoNIFTI Group_f_stat_masked+tlrc
  3dAFNItoNIFTI -prefix Positive_clustered_f_stat Group_positive_f_stat_clustered+tlrc
  3dAFNItoNIFTI mask+tlrc
